export const navLinks = [
  {url: "/home", label: "Sales"},
  {url: "/about-us", label: "Supplier"},
  {url: "/products", label: "Employee"},
  {url: "/contact-us", label: "Purchase"},
  {url: "/home", label: "Customer"},
  {url: "/about-us", label: "Accounts"},
  {url: "/products", label: "Discount"},
  {url: "/master", label: "Masters"},
  {url: "/home", label: "Conversation"},
  {url: "/about-us", label: "Weighment"},
  {url: "/products", label: "Reports"},
  {url: "/contact-us", label: "Operation"},
  {url: "/contact-us", label: "Vehicle"},
  {url: "/contact-us", label: "Crusher"},
  {url: "/contact-us", label: "Inventory"},
  {url: "/products", label: "Reports"},
  {url: "/contact-us", label: "Operation"},
  {url: "/contact-us", label: "Vehicle"},
];
